# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from repo_harvester_server.models.base_model_ import Model
from repo_harvester_server import util


class RepositoryInfo(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, repo_uri: str=None, re3data_id: str=None, metadata: Dict=None, services: Dict=None, policies: Dict=None):  # noqa: E501
        """RepositoryInfo - a model defined in Swagger

        :param repo_uri: The repo_uri of this RepositoryInfo.  # noqa: E501
        :type repo_uri: str
        :param re3data_id: The re3data_id of this RepositoryInfo.  # noqa: E501
        :type re3data_id: str
        :param metadata: The metadata of this RepositoryInfo.  # noqa: E501
        :type metadata: Dict
        :param services: The services of this RepositoryInfo.  # noqa: E501
        :type services: Dict
        :param policies: The policies of this RepositoryInfo.  # noqa: E501
        :type policies: Dict
        """
        self.swagger_types = {
            'repo_uri': str,
            're3data_id': str,
            'metadata': Dict,
            'services': Dict,
            'policies': Dict
        }

        self.attribute_map = {
            'repo_uri': 'repoURI',
            're3data_id': 're3dataID',
            'metadata': 'metadata',
            'services': 'services',
            'policies': 'policies'
        }
        self._repo_uri = repo_uri
        self._re3data_id = re3data_id
        self._metadata = metadata
        self._services = services
        self._policies = policies

    @classmethod
    def from_dict(cls, dikt) -> 'RepositoryInfo':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RepositoryInfo of this RepositoryInfo.  # noqa: E501
        :rtype: RepositoryInfo
        """
        return util.deserialize_model(dikt, cls)

    @property
    def repo_uri(self) -> str:
        """Gets the repo_uri of this RepositoryInfo.


        :return: The repo_uri of this RepositoryInfo.
        :rtype: str
        """
        return self._repo_uri

    @repo_uri.setter
    def repo_uri(self, repo_uri: str):
        """Sets the repo_uri of this RepositoryInfo.


        :param repo_uri: The repo_uri of this RepositoryInfo.
        :type repo_uri: str
        """

        self._repo_uri = repo_uri

    @property
    def re3data_id(self) -> str:
        """Gets the re3data_id of this RepositoryInfo.


        :return: The re3data_id of this RepositoryInfo.
        :rtype: str
        """
        return self._re3data_id

    @re3data_id.setter
    def re3data_id(self, re3data_id: str):
        """Sets the re3data_id of this RepositoryInfo.


        :param re3data_id: The re3data_id of this RepositoryInfo.
        :type re3data_id: str
        """

        self._re3data_id = re3data_id

    @property
    def metadata(self) -> Dict:
        """Gets the metadata of this RepositoryInfo.


        :return: The metadata of this RepositoryInfo.
        :rtype: Dict
        """
        return self._metadata

    @metadata.setter
    def metadata(self, metadata: Dict):
        """Sets the metadata of this RepositoryInfo.


        :param metadata: The metadata of this RepositoryInfo.
        :type metadata: Dict
        """

        self._metadata = metadata

    @property
    def services(self) -> Dict:
        """Gets the services of this RepositoryInfo.


        :return: The services of this RepositoryInfo.
        :rtype: Dict
        """
        return self._services

    @services.setter
    def services(self, services: Dict):
        """Sets the services of this RepositoryInfo.


        :param services: The services of this RepositoryInfo.
        :type services: Dict
        """

        self._services = services

    @property
    def policies(self) -> Dict:
        """Gets the policies of this RepositoryInfo.


        :return: The policies of this RepositoryInfo.
        :rtype: Dict
        """
        return self._policies

    @policies.setter
    def policies(self, policies: Dict):
        """Sets the policies of this RepositoryInfo.


        :param policies: The policies of this RepositoryInfo.
        :type policies: Dict
        """

        self._policies = policies
